version: "2"
services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
      - back-end

  vote:
    image: eesprit/voting-app-vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - back-end
      - front-end

  result:
    image: eesprit/voting-app-result
    ports:
      - 5001:80
    lepends_on:
      - db
    networks:
      - back-end
      - front-end

  worker:
    image: jplatorre/worker
    depends_on:
      - redis
      - db
    networks:
      - back-end

networks:
  front-end:
  back-end:
# links: is removed from this version and above version because here docker-compose creates a dedicated network and assigned to all containers
# and all containers communicates with each other by their name
# this version introduce "depends_on" feature to define the dependencies
